version: "3"

services:
  jenkins:
    image: jenkins/jenkins:lts
    restart: always
    ports:
      - "8080:8080"
      # - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      # - /var/jenkins_home:/var/jenkins_home
      # - /var/run/docker.sock:/var/run/docker.sock

  postgres:
    image: postgres:alpine
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonarpasswd
    volumes:
      - ddh-postgres:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@email.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - 5050:80

  sonarqube:
    image: sonarqube:lts
    restart: always
    ports:
      - "9000:9000"
      - "9092:9092"
    environment:
      SONARQUBE_JDBC_USERNAME: sonar
      SONARQUBE_JDBC_PASSWORD: sonarpasswd
      SONARQUBE_JDBC_URL: "jdbc:postgresql://postgres:5432/sonar"
    depends_on:
      - postgres

volumes:
  jenkins_home:
  ddh-postgres:
